name: Delete releases
on:
  workflow_dispatch:

jobs:
  Purge:
    runs-on: ubuntu-20.04
    if: ${{ github.repository_owner == 'Armbian' }}
    timeout-minutes: 480
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix: 
        include: # build this way: cat userdata.csv | cut -d"/" -f1 | uniq | sed 's/.*/          - board: &/'
          - board: bananapi
          - board: bananapim2plus
          - board: bananapim64
          - board: bananapipro
          - board: bananapi
          - board: clearfogbase
          - board: clearfogpro
          - board: cubox-i
          - board: firefly-rk3399
          - board: helios4
          - board: helios64
          - board: jethubj100
          - board: jethubj80
          - board: jetson-nano
          - board: khadas-edge
          - board: khadas-vim1
          - board: khadas-vim2
          - board: khadas-vim3
          - board: khadas-vim3l
          - board: khadas-vim3
          - board: lafrite
          - board: lepotato
          - board: lime2
          - board: lime-a64
          - board: nanopct4
          - board: nanopik1plus
          - board: nanopim4
          - board: nanopim4v2
          - board: nanopineo2black
          - board: nanopineo2
          - board: nanopineo
          - board: nanopineoplus2
          - board: nanopi-r1
          - board: nanopi-r2c
          - board: nanopi-r2s
          - board: nanopi-r4s
          - board: odroidc2
          - board: odroidc4
          - board: odroidhc4
          - board: odroidn2
          - board: odroidxu4
          - board: orangepi3
          - board: orangepi4
          - board: orangepilite2
          - board: orangepilite
          - board: orangepione
          - board: orangepioneplus
          - board: orangepipc2
          - board: orangepipc
          - board: orangepipcplus
          - board: orangepiplus2e
          - board: orangepiplus
          - board: orangepiprime
          - board: orangepi-r1
          - board: orangepi-r1plus-lts
          - board: orangepi-r1plus
          - board: orangepizero2
          - board: orangepizero
          - board: orangepizeroplus2-h3
          - board: orangepizeroplus
          - board: orangepizero
          - board: pine64
          - board: pinebook-a64
          - board: pinebook-pro
          - board: pineh64
          - board: quartz64a
          - board: radxa-zero
          - board: renegade
          - board: rk322x-box
          - board: rock-3a
          - board: rpi4b
          - board: station-m1
          - board: station-m2
          - board: station-p1
          - board: station-p2
          - board: tinkerboard-2
          - board: tinkerboard
          - board: uefi-arm64
          - board: uefi-x86
          - board: virtual-qemu
          - board: xt-q8l-v10
          - board: zeropi
    steps:
      - uses: igorpecovnik/delete-tag-and-release@master
        with:
          delete_release: true # default: false
          tag_name: ${{ matrix.board }} # tag name to delete
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
