name: Delete releases
on:
  workflow_dispatch:

jobs:
  Purge:
    runs-on: ubuntu-20.04
    if: ${{ github.repository_owner == 'Armbian' }}
    timeout-minutes: 480
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix: 
        include: # build this way: cat userdata.csv | cut -d"/" -f1 | uniq | sed 's/.*/          - board: &/'
          - board: bananapi
          - board: bananapim2plus
          - board: bananapim2ultra
          - board: bananapim2zero
          - board: bananapim3
          - board: bananapim64
          - board: bananapipro
          - board: bananapir2
          - board: clearfogbase
          - board: clearfogpro
          - board: cubieboard
          - board: cubieboard2
          - board: cubietruck
          - board: cubox-i
          - board: espressobin
          - board: fe-som-rk3399
          - board: firefly-rk3399
          - board: helios4
          - board: helios64
          - board: jethubj100
          - board: jethubj80
          - board: jetson-nano
          - board: khadas-edge
          - board: khadas-vim1
          - board: khadas-vim2
          - board: khadas-vim3
          - board: khadas-vim3l
          - board: lafrite
          - board: lepotato
          - board: lime-a10
          - board: lime-a64
          - board: lime
          - board: lime2
          - board: macchiatobin-doubleshot
          - board: micro
          - board: miqi
          - board: nanopct3
          - board: nanopct3plus
          - board: nanopct4
          - board: nanopi-r1
          - board: nanopi-r2s
          - board: nanopi-r4s
          - board: nanopia64
          - board: nanopiair
          - board: nanopiduo
          - board: nanopiduo2
          - board: nanopifire3
          - board: nanopik1plus
          - board: nanopik2-s905
          - board: nanopim1
          - board: nanopim1plus
          - board: nanopim3
          - board: nanopim4
          - board: nanopim4v2
          - board: nanopineo
          - board: nanopineo2
          - board: nanopineo2black
          - board: nanopineo3
          - board: nanopineo4
          - board: nanopineocore2
          - board: nanopineoplus2
          - board: odroidc1
          - board: odroidc2
          - board: odroidc4
          - board: odroidhc4
          - board: odroidn2
          - board: odroidxu4
          - board: orangepi-r1
          - board: orangepi-r1plus
          - board: orangepi-rk3399
          - board: orangepi2
          - board: orangepi3
          - board: orangepi4
          - board: orangepilite
          - board: orangepilite2
          - board: orangepione
          - board: orangepioneplus
          - board: orangepipc
          - board: orangepipc2
          - board: orangepipcplus
          - board: orangepiplus
          - board: orangepiplus2e
          - board: orangepiprime
          - board: orangepiwin
          - board: orangepizero
          - board: orangepizero2
          - board: orangepizeroplus
          - board: orangepizeroplus2-h3
          - board: orangepizeroplus2-h5
          - board: pcduino3
          - board: pine64
          - board: pine64so
          - board: pinebook-a64
          - board: pinebook-pro
          - board: pinecube
          - board: pineh64-b
          - board: pineh64
          - board: radxa-zero
          - board: renegade
          - board: rk322x-box
          - board: rock-3a
          - board: rock64
          - board: rockpi-4a
          - board: rockpi-4b
          - board: rockpi-4c
          - board: rockpi-e
          - board: rockpi-n10
          - board: rockpi-s
          - board: rockpro64
          - board: station-m1
          - board: station-p1
          - board: teres-a64
          - board: tinkerboard
          - board: tritium-h3
          - board: tritium-h5
          - board: udoo
          - board: virtual-qemu
          - board: xt-q8l-v10
          - board: z28pro
          - board: zeropi
    steps:
      - uses: igorpecovnik/delete-tag-and-release@master
        with:
          delete_release: true # default: false
          tag_name: ${{ matrix.board }} # tag name to delete
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
