name: Delete releases
on:
  workflow_dispatch:

jobs:
  Purge:
    runs-on: ubuntu-20.04
    if: ${{ github.repository_owner == 'Armbian' }}
    timeout-minutes: 480
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix: 
        include: # build this way: cat userdata.csv | cut -d"/" -f1 | uniq | sed 's/.*/          - board: &/'
          - board: aml-s9xx-box
          - board: bananapicm4io
          - board: bananapim1plus
          - board: bananapim2plus
          - board: bananapim2pro
          - board: bananapim2s
          - board: bananapim2ultra
          - board: bananapim2zero
          - board: bananapim3
          - board: bananapim5
          - board: bananapim64
          - board: bananapipro
          - board: bananapir2pro
          - board: beelinkx2
          - board: bigtreetech-cb1
          - board: clearfogbase
          - board: clearfogpro
          - board: clockworkpi-a06
          - board: cubieboard2
          - board: cubieboard4
          - board: cubieboard
          - board: cubietruck
          - board: cubietruckplus
          - board: cubox-i
          - board: espressobin
          - board: firefly-rk3399
          - board: helios4
          - board: helios64
          - board: jethubj100
          - board: jethubj80
          - board: jetson-nano
          - board: khadas-edge2
          - board: khadas-edge
          - board: khadas-vim1
          - board: khadas-vim2
          - board: khadas-vim3
          - board: khadas-vim3l
          - board: lafrite
          - board: lepotato
          - board: lime2
          - board: lime-a33
          - board: lime-a64
          - board: lime
          - board: mekotronics-r58-minipc
          - board: mekotronics-r58x-4g
          - board: mekotronics-r58x
          - board: melea1000
          - board: micro
          - board: nanopct4
          - board: nanopia64
          - board: nanopiair
          - board: nanopiduo2
          - board: nanopiduo
          - board: nanopik1plus
          - board: nanopik2-s905
          - board: nanopim4
          - board: nanopim4v2
          - board: nanopineo2
          - board: nanopineo2black
          - board: nanopineo3
          - board: nanopineo4
          - board: nanopineo
          - board: nanopineocore2
          - board: nanopineoplus2
          - board: nanopi-r1
          - board: nanopi-r1s-h5
          - board: nanopi-r2c
          - board: nanopi-r2s
          - board: nanopi-r4s
          - board: nanopi-r4se
          - board: nanopi-r6s
          - board: odroidc2
          - board: odroidc4
          - board: odroidhc4
          - board: odroidm1
          - board: odroidn2
          - board: odroidxu4
          - board: olimex-teres-a64
          - board: onecloud
          - board: orangepi2
          - board: orangepi3-lts
          - board: orangepi4
          - board: orangepi4-lts
          - board: orangepi5
          - board: orangepi5-plus
          - board: orangepilite2
          - board: orangepione
          - board: orangepioneplus
          - board: orangepipc2
          - board: orangepipc
          - board: orangepipcplus
          - board: orangepiplus2e
          - board: orangepiprime
          - board: orangepi-r1
          - board: orangepi-r1plus
          - board: orangepi-r1plus-lts
          - board: orangepi-rk3399
          - board: orangepiwin
          - board: orangepizero2
          - board: orangepizero
          - board: orangepizeroplus2-h3
          - board: orangepizeroplus2-h5
          - board: orangepizeroplus
          - board: panther-x2
          - board: pcduino3
          - board: pine64
          - board: pine64so
          - board: pinebook-a64
          - board: pinebook-pro
          - board: pinecube
          - board: pineh64
          - board: pineh64-b
          - board: quartz64a
          - board: quartz64b
          - board: radxa-e25
          - board: radxa-zero2
          - board: radxa-zero
          - board: recore
          - board: renegade
          - board: rk322x-box
          - board: rk3318-box
          - board: rock-3a
          - board: rock-5a
          - board: rock-5b
          - board: rock64
          - board: rockpi-4a
          - board: rockpi-4b
          - board: rockpi-4c
          - board: rockpi-4cplus
          - board: rockpi-e
          - board: rockpi-n10
          - board: rockpi-s
          - board: rockpro64
          - board: roc-rk3399-pc
          - board: rpi4b
          - board: sk-am64b
          - board: station-m1
          - board: station-m2
          - board: station-m3
          - board: station-p1
          - board: station-p2
          - board: sunvell-r69
          - board: thinkpad-x13s
          - board: tinkerboard-2
          - board: tinkerboard
          - board: tritium-h3
          - board: tritium-h5
          - board: udoo
          - board: uefi-arm64
          - board: uefi-riscv64
          - board: uefi-x86
          - board: xt-q8l-v10
          - board: zeropi
          - board: star64
          - board: aml-s9xx-box
          - board: mangopi-mq
          - board: nezha
          - board: unmatched
          - board: nezha
          - board: unmatched
          - board: khadas-vim1
          - board: rock-3a
          - board: orangepilite2
          - board: beaglev
          - board: rock-3a
          - board: beaglev
          - board: rockpi-n10
          - board: rock-3a
          - board: rk3318-box
          - board: orangepioneplus
          - board: visionfive
          - board: orangepilite2
          - board: visionfive
          - board: jethubj100
          - board: nanopi-r4se
          - board: rock-3a
          - board: rockpi-n10
          - board: rk3318-box
          - board: orangepioneplus
          - board: rk3318-box
          - board: orangepioneplus
          - board: jethubj100
          - board: nanopi-r4s
          - board: pineh64
          - board: nanopi-r4s
          - board: orangepi3-lts
          - board: jetson-nano
          - board: radxa-zero2
          - board: onecloud
          - board: jetson-nano
          - board: orangepi3-lts
          - board: radxa-zero2
          - board: rk322x-box
          - board: khadas-vim3
          - board: cubietruckplus
          - board: rk322x-box
          - board: cubieboard4
          - board: cubietruckplus
          - board: nanopiduo2
          - board: beelinkx2
          - board: orangepipcplus
          - board: orangepi-r1
          - board: cubietruck
          - board: nanopiduo2
          - board: cubieboard4
          - board: beelinkx2
          - board: orangepipcplus
          - board: cubietruck
          - board: orangepi-r1
          - board: cubietruck
          - board: orangepi-r1
          - board: station-m2
          - board: helios4
          - board: bananapim2ultra
          - board: pineh64
          - board: orangepi5-plus
          - board: pineh64
          - board: helios4
          - board: bananapim2ultra
          - board: orangepi5-plus
          - board: nanopi-r6s
          - board: khadas-vim3l
          - board: khadas-vim2
          - board: radxa-zero
          - board: khadas-vim3
          - board: nanopi-r6s
          - board: orangepi4-lts
          - board: orangepi2
          - board: orangepi3
          - board: nanopiduo
          - board: orangepi2
          - board: radxa-zero
          - board: khadas-vim2
          - board: nanopiduo
          - board: orangepi4-lts
          - board: orangepi3
          - board: station-m2
          - board: rock-5b
          - board: orangepi-r1plus-lts
          - board: rock-5b
          - board: cubieboard2
          - board: orangepipc
          - board: orangepi-r1plus-lts
          - board: orangepi4-lts
          - board: rock-5b
          - board: cubieboard2
          - board: orangepipc
          - board: orangepione
          - board: rock-5b
          - board: orangepi4-lts
          - board: orangepizero2
          - board: uefi-riscv64
          - board: orangepione
          - board: orangepizero2
          - board: roc-rk3399-pc
          - board: clockworkpi-a06
          - board: khadas-vim2
          - board: jethubj80
          - board: uefi-riscv64
          - board: clockworkpi-a06
          - board: recore
          - board: khadas-vim2
          - board: jethubj80
          - board: recore
          - board: bananapim2zero
          - board: bananapim2ultra
          - board: bananapim2zero
          - board: khadas-vim1
          - board: bananapim2ultra
          - board: orangepipc
          - board: orangepi4
          - board: odroidm1
          - board: orangepi-r1plus
          - board: orangepi4
          - board: odroidm1
          - board: bananapim5
          - board: orangepipc
          - board: orangepi-r1plus
          - board: bananapim5
          - board: pineh64
          - board: khadas-vim1
          - board: pineh64
          - board: espressobin
          - board: orangepipc2
          - board: espressobin
          - board: orangepipc2
          - board: pineh64-b
          - board: radxa-zero
          - board: rock64
          - board: pinebook-pro
          - board: nanopi-r6s
          - board: radxa-zero
          - board: orangepipcplus
          - board: orangepizeroplus2-h5
          - board: orangepiprime
          - board: nanopi-r6s
          - board: orangepizeroplus2-h5
          - board: orangepipcplus
          - board: orangepizeroplus2-h5
          - board: orangepipcplus
          - board: pinebook-pro
          - board: station-m1
          - board: orangepiprime
          - board: station-m1
          - board: orangepizero
          - board: pineh64-b
          - board: orangepizero
          - board: khadas-edge2
          - board: rock64
          - board: bananapim2zero
          - board: sunvell-r69
          - board: bananapim2zero
          - board: bananapim1plus
          - board: sunvell-r69
          - board: bananapim1plus
          - board: pinebook-pro
          - board: station-m1
          - board: renegade
          - board: khadas-edge2
          - board: tritium-h5
          - board: pinebook-pro
          - board: station-m1
          - board: renegade
          - board: khadas-vim3
          - board: renegade
          - board: khadas-vim3
          - board: nanopineo2black
          - board: tritium-h5
          - board: nanopineo2black
          - board: renegade
          - board: nanopineo2black
          - board: renegade
          - board: bananapim2pro
          - board: mekotronics-r58-minipc
          - board: tinkerboard
          - board: bananapim2pro
          - board: station-p1
          - board: tinkerboard
          - board: rockpi-4a
          - board: rockpi-4c
          - board: nanopineo4
          - board: khadas-vim3l
          - board: rockpi-4a
          - board: lime
          - board: bananapim64
          - board: lime
          - board: bananapim64
          - board: melea1000
          - board: rockpi-4c
          - board: pineh64-b
          - board: rockpi-4b
          - board: melea1000
          - board: rock64
          - board: pineh64-b
          - board: rock64
          - board: mekotronics-r58-minipc
          - board: cubox-i
          - board: khadas-vim3l
          - board: orangepi-rk3399
          - board: uefi-x86
          - board: cubox-i
          - board: orangepi-rk3399
          - board: orangepizeroplus
          - board: micro
          - board: station-m2
          - board: nanopineo
          - board: station-m3
          - board: station-m2
          - board: uefi-x86
          - board: nanopineo
          - board: uefi-x86
          - board: nanopineo
          - board: tritium-h3
          - board: lime
          - board: udoo
          - board: lime2
          - board: tritium-h3
          - board: udoo
          - board: lime2
          - board: station-p1
          - board: lime2
          - board: station-p1
          - board: lime
          - board: orangepizeroplus
          - board: tinkerboard
          - board: orangepizeroplus
          - board: tritium-h3
          - board: nanopineo3
          - board: station-m3
          - board: tinkerboard-2
          - board: nanopineo3
          - board: tritium-h3
          - board: nanopineo3
          - board: tritium-h3
          - board: nanopineo4
          - board: tinkerboard
          - board: nanopineo4
          - board: tinkerboard
          - board: tinkerboard-2
          - board: rockpi-4b
          - board: mekotronics-r58x
          - board: khadas-edge2
          - board: rockpi-4c
          - board: khadas-edge2
          - board: mekotronics-r58x-4g
          - board: nanopineocore2
          - board: rockpi-4c
          - board: orangepiwin
          - board: firefly-rk3399
          - board: pcduino3
          - board: firefly-rk3399
          - board: odroidxu4
          - board: pcduino3
          - board: bananapim1plus
          - board: odroidxu4
          - board: nanopineoplus2
          - board: pine64so
          - board: orangepizeroplus2-h3
          - board: pine64so
          - board: lime-a33
          - board: orangepizeroplus2-h3
          - board: bananapim1plus
          - board: lime-a33
          - board: lafrite
          - board: panther-x2
          - board: rockpi-e
          - board: uefi-x86
          - board: mekotronics-r58x
          - board: panther-x2
          - board: lime-a64
          - board: mekotronics-r58x
          - board: radxa-e25
          - board: uefi-x86
          - board: rockpi-e
          - board: radxa-e25
          - board: station-p1
          - board: lime-a64
          - board: mekotronics-r58-minipc
          - board: station-p1
          - board: odroidc2
          - board: rockpro64
          - board: odroidc2
          - board: nanopineo2
          - board: rockpro64
          - board: nanopineo2
          - board: uefi-arm64
          - board: bananapim2plus
          - board: nanopineo4
          - board: bananapim2plus
          - board: nanopineo4
          - board: nanopim4v2
          - board: pine64
          - board: clearfogpro
          - board: rockpi-s
          - board: clearfogpro
          - board: bananapim2pro
          - board: rockpi-s
          - board: odroidc4
          - board: rockpi-s
          - board: nanopi-r2c
          - board: bananapim2pro
          - board: lime2
          - board: bananapipro
          - board: bananapim64
          - board: bananapipro
          - board: lime2
          - board: odroidhc4
          - board: lime2
          - board: bananapipro
          - board: pine64
          - board: bigtreetech-cb1
          - board: lepotato
          - board: odroidc4
          - board: station-p2
          - board: bananapim2plus
          - board: bigtreetech-cb1
          - board: bananapim2plus
          - board: lepotato
          - board: bananapim2plus
          - board: lepotato
          - board: station-p2
          - board: rpi4b
          - board: bananapim64
          - board: uefi-arm64
          - board: nanopim4v2
          - board: odroidhc4
          - board: rpi4b
          - board: bananapicm4io
          - board: lime-a64
          - board: bananapicm4io
          - board: lime-a64
          - board: rk322x-box
          - board: nanopiair
          - board: rock-3a
          - board: nanopiair
          - board: rock-3a
          - board: nanopik1plus
          - board: pinecube
          - board: bananapir2pro
          - board: pinecube
          - board: odroidxu4
          - board: nanopct4
          - board: bananapir2pro
          - board: nanopi-r2s
          - board: nanopct4
          - board: odroidc4
          - board: nanopct4
          - board: bananapir2pro
          - board: bigtreetech-cb1
          - board: odroidn2
          - board: bigtreetech-cb1
          - board: odroidc4
          - board: nanopia64
          - board: bananapir2pro
          - board: nanopia64
          - board: nanopik2-s905
          - board: odroidn2
          - board: orangepi3-lts
          - board: nanopik2-s905
          - board: nanopim4
          - board: orangepi3-lts
          - board: pinebook-a64
          - board: onecloud
          - board: nanopim4
          - board: pinebook-a64
          - board: onecloud
          - board: bananapim3
          - board: radxa-e25
          - board: orangepiplus2e
          - board: orangepi5
          - board: orangepione
          - board: nanopi-r1
          - board: nanopim4
          - board: orangepi5
          - board: orangepiplus2e
          - board: radxa-e25
          - board: nanopi-r1
          - board: radxa-e25
          - board: nanopi-r1
          - board: cubieboard
          - board: lepotato
          - board: nanopim4
          - board: jetson-nano
          - board: rockpi-4b
          - board: mekotronics-r58x-4g
          - board: orangepione
          - board: lepotato
          - board: cubieboard
          - board: olimex-teres-a64
          - board: rockpi-4b
          - board: rockpro64
          - board: uefi-arm64
          - board: zeropi
          - board: mekotronics-r58x-4g
          - board: rockpro64
          - board: zeropi
          - board: quartz64a
          - board: zeropi
          - board: quartz64b
          - board: olimex-teres-a64
          - board: lafrite
          - board: quartz64b
          - board: quartz64a
          - board: quartz64b
          - board: quartz64a
          - board: orangepioneplus
          - board: uefi-arm64
          - board: xt-q8l-v10
          - board: station-p2
          - board: olimex-teres-a64
          - board: xt-q8l-v10
          - board: jetson-nano
          - board: orangepiplus2e
          - board: nanopim4v2
          - board: orangepiplus2e
          - board: nanopi-r1s-h5
          - board: clearfogbase
          - board: odroidc2
          - board: odroidn2
          - board: orangepi5
          - board: olimex-teres-a64
          - board: odroidn2
          - board: odroidc2
          - board: orangepi5
          - board: odroidhc4
          - board: nanopct4
          - board: nanopi-r1s-h5
          - board: station-p2
          - board: nanopim4v2
          - board: odroidhc4
          - board: rock-3a
          - board: nanopct4
          - board: lafrite
          - board: orangepioneplus
          - board: lafrite
          - board: orangepioneplus
          - board: rock-3a
          - board: orangepilite2
          - board: orangepi4
          - board: orangepilite2
          - board: bananapim2s
          - board: orangepi4
          - board: bananapim2s
          - board: rk3318-box
          - board: aml-s9xx-box
          - board: orangepi5-plus
          - board: aml-s9xx-box
          - board: odroidm1
          - board: orangepi5-plus
          - board: odroidm1
          - board: unleashed
          - board: visionfive2
          - board: tritium-h5
          - board: station-m3
          - board: rockpi-4a
          - board: station-m3
          - board: rockpi-4a
          - board: bananapim5
          - board: bananapim2s
          - board: bananapim5
          - board: bananapim2s
          - board: khadas-edge
          - board: pine64
          - board: firefly-rk3399
    steps:
      - uses: igorpecovnik/delete-tag-and-release@master
        with:
          delete_release: true # default: false
          tag_name: ${{ matrix.board }} # tag name to delete
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
