name: Delete rootfs cache
on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  Purge:
    runs-on: ubuntu-20.04
    if: ${{ github.repository_owner == 'Armbian' }}
    timeout-minutes: 10
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix: 
        include: # build this way: cat userdata.csv | cut -d"/" -f1 | uniq | sed 's/.*/          - board: &/'
          - board: _rootfs
    steps:
      - uses: igorpecovnik/delete-tag-and-release@master
        with:
          delete_release: true # default: false
          tag_name: ${{ matrix.board }} # tag name to delete
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
